name: Build

on: [ push,pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: Build Cirrus API
        run: mvn install:install-file -Dfile=ace-velocity/libs/cirrus-api-3.0.0-SNAPSHOT.jar -DgroupId=dev.simplex.cirrus -DartifactId=cirrus-api -Dversion=3.0.0-SNAPSHOT -Dpackaging=jar -DgeneratePom=true
      - name: Build Cirrus Velocity
        run: mvn install:install-file -Dfile=ace-velocity/libs/cirrus-velocity-3.0.0-SNAPSHOT.jar -DgroupId=dev.simplex.cirrus -DartifactId=cirrus-velocity -Dversion=3.0.0-SNAPSHOT -Dpackaging=jar -DgeneratePom=true

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ace-prod
          path: |
            ace-spigot/target/ace-spigot.jar
            ace-velocity/target/ace-velocity.jar